# Generated by Django 5.0.1 on 2024-01-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_products_options_color_gallery_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Galleries'},
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.FileField(default='product.jpg', upload_to='products'),
        ),
    ]
