# Generated by Django 5.0.1 on 2024-01-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_coupon_notifications_productsfaq_review_wishtlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
