# Generated by Django 5.0.1 on 2024-01-06 15:07

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auths', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890abcdefghijklmnop', length=10, max_length=10, prefix='', unique=True),
        ),
    ]
