# Generated by Django 5.0.1 on 2024-01-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auths', '0003_alter_profile_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
